# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lambda_rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lambda_rpc.proto',
  package='lambdagrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x10lambda_rpc.proto\x12\nlambdagrpc\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\"=\n\rInvokeRequest\x12,\n\x0e\x63lient_request\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"c\n\x0eInvokeResponse\x12-\n\x0f\x63lient_response\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.google.rpc.Statusb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_rpc_dot_status__pb2.DESCRIPTOR,])




_INVOKEREQUEST = _descriptor.Descriptor(
  name='InvokeRequest',
  full_name='lambdagrpc.InvokeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_request', full_name='lambdagrpc.InvokeRequest.client_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=145,
)


_INVOKERESPONSE = _descriptor.Descriptor(
  name='InvokeResponse',
  full_name='lambdagrpc.InvokeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_response', full_name='lambdagrpc.InvokeResponse.client_response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='lambdagrpc.InvokeResponse.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=246,
)

_INVOKEREQUEST.fields_by_name['client_request'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_INVOKERESPONSE.fields_by_name['client_response'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_INVOKERESPONSE.fields_by_name['status'].message_type = google_dot_rpc_dot_status__pb2._STATUS
DESCRIPTOR.message_types_by_name['InvokeRequest'] = _INVOKEREQUEST
DESCRIPTOR.message_types_by_name['InvokeResponse'] = _INVOKERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InvokeRequest = _reflection.GeneratedProtocolMessageType('InvokeRequest', (_message.Message,), dict(
  DESCRIPTOR = _INVOKEREQUEST,
  __module__ = 'lambda_rpc_pb2'
  # @@protoc_insertion_point(class_scope:lambdagrpc.InvokeRequest)
  ))
_sym_db.RegisterMessage(InvokeRequest)

InvokeResponse = _reflection.GeneratedProtocolMessageType('InvokeResponse', (_message.Message,), dict(
  DESCRIPTOR = _INVOKERESPONSE,
  __module__ = 'lambda_rpc_pb2'
  # @@protoc_insertion_point(class_scope:lambdagrpc.InvokeResponse)
  ))
_sym_db.RegisterMessage(InvokeResponse)


# @@protoc_insertion_point(module_scope)
